require "user.lsp"
require "user.keymaps"
require "user.options"
require "user.plugins"
require "user.plugin_config.cmp"
require "user.plugin_config.colorscheme"
require "user.plugin_config.jabs"
require "user.plugin_config.dashboard"
